Q1. Handle Missing Values (Basic Cleaning)
Fill missing values using the following:
Age → Median
Salary → Mean
Hours_Worked_Per_Week → Median
Performance_Score → Mean
Display the dataset after handling missing values

In [86]:
import pandas as pd
df=pd.read_csv('employee_productivity_dataset.csv')
df['Age'].fillna(df['Age'].median(),inplace=True)
df['Salary'].fillna(df['Salary'].mean(),inplace=True)
df['Hours_Worked_Per_Week'].fillna(df['Hours_Worked_Per_Week'].median(),inplace=True)
df['Performance_Score'].fillna(df['Performance_Score'].mean(),inplace=True)
print(df.head())

  Employee_ID         Name Department   Age  Gender Work_Mode   Join_Date  \
0        E001  Amit Sharma         IT  25.0    Male    Remote  15-01-2021
1        E002   Riya Patel         HR  30.0  Female    Hybrid  15-02-2020
2        E003  John Mathew    Finance  29.0    Male    Onsite  10-03-2022
3        E004  Sneha Joshi         IT  28.0  Female    Remote  22-04-2021
4        E005  Arjun Verma  Marketing  35.0    Male    Hybrid  18-05-2020

   Hours_Worked_Per_Week  Projects_Completed  Performance_Score        Salary  \
0                   40.0                   5             4.5000  50000.000000
1                   38.0                   4             4.0000  45000.000000
2                   45.0                   6             4.3125  60000.000000
3                   41.0                   5             4.2000  52000.000000
4                   50.0                   7             4.8000  50666.666667

    Location
0       Pune
1     Mumbai
2  Bangalore
3      Delhi
4       Pune

/tmp/ipykernel_1755/4168613555.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(),inplace=True)
/tmp/ipykernel_1755/4168613555.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(),inplace=True)
/tmp/ipykernel_1755/4168613555.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Hours_Worked_Per_Week'].fillna(df['Hours_Worked_Per_Week'].median(),inplace=True)
/tmp/ipykernel_1755/4168613555.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Performance_Score'].fillna(df['Performance_Score'].mean(),inplace=True)

Q2. Label Encoding
Convert these columns into numeric values using Label Encoding:
Gender
Department
Show the updated columns.

In [87]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df['Department']=le.fit_transform(df['Department'])
df[['Gender','Department']]

     Gender  Department
0         1           2
1         0           1
2         1           0
3         0           2
4         1           3
..      ...         ...
245       0           1
246       1           0
247       0           3
248       1           2
249       0           1

[250 rows x 2 columns]

Q3. One-Hot Encoding
Apply One-Hot Encoding on:
Work_Mode
Location
Display the dataset and check how many new columns are created.

In [88]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
ohe = OneHotEncoder(sparse_output=False)
encoded_data = ohe.fit_transform(df[['Work_Mode', 'Location']])
new_columns = ohe.get_feature_names_out(['Work_Mode', 'Location'])
encoded_df = pd.DataFrame(encoded_data, columns=new_columns, index=df.index)
df = pd.concat([df.drop(columns=['Work_Mode', 'Location']), encoded_df], axis=1)
print(df.head())
print(f"Number of new columns created: {len(new_columns)}")

  Employee_ID         Name  Department   Age  Gender   Join_Date  \
0        E001  Amit Sharma           2  25.0       1  15-01-2021
1        E002   Riya Patel           1  30.0       0  15-02-2020
2        E003  John Mathew           0  29.0       1  10-03-2022
3        E004  Sneha Joshi           2  28.0       0  22-04-2021
4        E005  Arjun Verma           3  35.0       1  18-05-2020

   Hours_Worked_Per_Week  Projects_Completed  Performance_Score        Salary  \
0                   40.0                   5             4.5000  50000.000000
1                   38.0                   4             4.0000  45000.000000
2                   45.0                   6             4.3125  60000.000000
3                   41.0                   5             4.2000  52000.000000
4                   50.0                   7             4.8000  50666.666667

   Work_Mode_Hybrid  Work_Mode_Onsite  Work_Mode_Remote  Location_Bangalore  \
0               0.0               0.0               1.0                 0.0
1               1.0               0.0               0.0                 0.0
2               0.0               1.0               0.0                 1.0
3               0.0               0.0               1.0                 0.0
4               1.0               0.0               0.0                 0.0

   Location_Delhi  Location_Mumbai  Location_Pune
0             0.0              0.0            1.0
1             0.0              1.0            0.0
2             0.0              0.0            0.0
3             1.0              0.0            0.0
4             0.0              0.0            1.0
Number of new columns created: 7

Q4. Normalization (Min-Max Scaling)
Normalize the following columns:
Salary
Hours_Worked_Per_Week
Use MinMaxScaler and display results.

In [89]:
from sklearn.preprocessing import MinMaxScaler
ms=MinMaxScaler()
df['Salary']=ms.fit_transform(df[['Salary']])
df['Hours_Worked_Per_Week']=ms.fit_transform(df[['Hours_Worked_Per_Week']])
df[['Salary','Hours_Worked_Per_Week']]

       Salary  Hours_Worked_Per_Week
0    0.347826               0.285714
1    0.130435               0.142857
2    0.782609               0.642857
3    0.434783               0.357143
4    0.376812               1.000000
..        ...                    ...
245  0.000000               0.000000
246  1.000000               0.857143
247  0.260870               0.428571
248  0.391304               0.357143
249  0.043478               0.071429

[250 rows x 2 columns]

Q5. Standardization (Scaling)
Apply StandardScaler on:
Age
Projects_Completed
Display the transformed values.

In [90]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
df['Age']=ss.fit_transform(df[['Age']])
df['Projects_Completed']=ss.fit_transform(df[['Projects_Completed']])
df[['Age','Projects_Completed']]

          Age  Projects_Completed
0   -1.172018           -0.211604
1    0.000000           -0.916949
2   -0.234404            0.493742
3   -0.468807           -0.211604
4    1.172018            1.199088
..        ...                 ...
245 -0.703211           -1.622295
246  2.344036            1.904433
247 -0.234404            0.493742
248  0.234404           -0.211604
249 -0.937614           -0.916949

[250 rows x 2 columns]

Q6. Compare Scaling Methods
Apply both:
MinMaxScaler
StandardScaler
On the Salary column.
Show both results side by side.

In [91]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler
ms=MinMaxScaler()
ss=StandardScaler()
df['Salary_MinMax']=ms.fit_transform(df[['Salary']])
df['Salary_Standard']=ss.fit_transform(df[['Salary']])
df[['Salary','Salary_MinMax','Salary_Standard']]

       Salary  Salary_MinMax  Salary_Standard
0    0.347826       0.347826    -9.745089e-02
1    0.130435       0.130435    -8.283326e-01
2    0.782609       0.782609     1.364312e+00
3    0.434783       0.434783     1.949018e-01
4    0.376812       0.376812    -3.732632e-16
..        ...            ...              ...
245  0.000000       0.000000    -1.266862e+00
246  1.000000       1.000000     2.095194e+00
247  0.260870       0.260870    -3.898036e-01
248  0.391304       0.391304     4.872545e-02
249  0.043478       0.043478    -1.120685e+00

[250 rows x 3 columns]

Q7. Build Preprocessing Pipeline
Create a pipeline that:
Applies encoding to categorical columns
Applies scaling to numerical columns
Use:
ColumnTransformer
Pipeline

In [92]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
numerical_cols = ['Age', 'Hours_Worked_Per_Week', 'Projects_Completed', 'Performance_Score', 'Salary']
categorical_cols = ['Department', 'Gender', 'Work_Mode', 'Location']
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_cols),
        ('cat', OneHotEncoder(), categorical_cols)
    ])
pipeline = Pipeline(steps=[('preprocessor', preprocessor)])
pipeline

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Age',
                                                   'Hours_Worked_Per_Week',
                                                   'Projects_Completed',
                                                   'Performance_Score',
                                                   'Salary']),
                                                 ('cat', OneHotEncoder(),
                                                  ['Department', 'Gender',
                                                   'Work_Mode',
                                                   'Location'])]))])

Q8. Apply Pipeline
Apply the pipeline on the dataset.
Display:
Transformed dataset
Shape of final dataset

In [93]:
df = pd.read_csv('employee_productivity_dataset.csv')
processed_data = pipeline.fit_transform(df)
cat_feature_names = pipeline.named_steps['preprocessor'].named_transformers_['cat'].get_feature_names_out(categorical_cols)
all_feature_names = numerical_cols + list(cat_feature_names)
df_processed = pd.DataFrame(processed_data, columns=all_feature_names)
print("--- Transformed Dataset ---")
print(df_processed.head())
print("--- Shape of Final Dataset ---")
print(df_processed.shape)

--- Transformed Dataset ---
        Age  Hours_Worked_Per_Week  Projects_Completed  Performance_Score  \
0 -1.140068              -0.410391           -0.211604           0.612883
1 -0.024784              -0.820783           -0.916949          -1.021472
2       NaN               0.615587            0.493742                NaN
3 -0.470898                    NaN           -0.211604          -0.367730
4  1.090500               1.641565            1.199088           1.593497

     Salary  Department_Finance  Department_HR  Department_IT  \
0 -0.092450                 0.0            0.0            1.0
1 -0.785825                 0.0            1.0            0.0
2  1.294300                 1.0            0.0            0.0
3  0.184900                 0.0            0.0            1.0
4       NaN                 0.0            0.0            0.0

   Department_Marketing  Gender_Female  Gender_Male  Work_Mode_Hybrid  \
0                   0.0            0.0          1.0               0.0
1                   0.0            1.0          0.0               1.0
2                   0.0            0.0          1.0               0.0
3                   0.0            1.0          0.0               0.0
4                   1.0            0.0          1.0               1.0

   Work_Mode_Onsite  Work_Mode_Remote  Location_Bangalore  Location_Delhi  \
0               0.0               1.0                 0.0             0.0
1               0.0               0.0                 0.0             0.0
2               1.0               0.0                 1.0             0.0
3               0.0               1.0                 0.0             1.0
4               0.0               0.0                 0.0             0.0

   Location_Mumbai  Location_Pune
0              0.0            1.0
1              1.0            0.0
2              0.0            0.0
3              0.0            0.0
4              0.0            1.0
--- Shape of Final Dataset ---
(250, 18)

Q9. Conceptual Question
Why is scaling important in Python?

Scaling is critical in machine learning because most algorithms rely on mathematical calculations (like calculating the distance between data points). If your dataset has features with vastly different ranges—such as a Performance_Score between 1 and 5, and a Salary between 40,000 and 100,000—the algorithm will unfairly prioritize the larger numbers. The model would treat Salary as much more important simply because of its magnitude. Scaling (like Standardization or Normalization) forces all numerical features onto a similar scale, ensuring every feature contributes equally to the model's predictions and allowing algorithms to process the data much faster.

Q10. Conceptual Question
Why do we convert categorical data into numerical form?

Machine learning models are fundamentally mathematical equations; they cannot read or understand text strings like "Remote", "Finance", or "Delhi". They only understand numbers. We must convert categorical data into a numerical format (using techniques like One-Hot Encoding or Label Encoding) to translate those text values into a language the algorithm can process, calculate, and ultimately use to find patterns.